// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: io/github/aaronai/greeting.proto

package io.github.aaronai.proto;

public final class GreetingOuterClass {
  private GreetingOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SayHelloRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.github.aaronai.proto.SayHelloRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string request_content = 1;</code>
     * @return The requestContent.
     */
    java.lang.String getRequestContent();
    /**
     * <code>string request_content = 1;</code>
     * @return The bytes for requestContent.
     */
    com.google.protobuf.ByteString
        getRequestContentBytes();
  }
  /**
   * Protobuf type {@code io.github.aaronai.proto.SayHelloRequest}
   */
  public static final class SayHelloRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.github.aaronai.proto.SayHelloRequest)
      SayHelloRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SayHelloRequest.newBuilder() to construct.
    private SayHelloRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SayHelloRequest() {
      requestContent_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SayHelloRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.aaronai.proto.GreetingOuterClass.internal_static_io_github_aaronai_proto_SayHelloRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.aaronai.proto.GreetingOuterClass.internal_static_io_github_aaronai_proto_SayHelloRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest.class, io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest.Builder.class);
    }

    public static final int REQUEST_CONTENT_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object requestContent_ = "";
    /**
     * <code>string request_content = 1;</code>
     * @return The requestContent.
     */
    @java.lang.Override
    public java.lang.String getRequestContent() {
      java.lang.Object ref = requestContent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestContent_ = s;
        return s;
      }
    }
    /**
     * <code>string request_content = 1;</code>
     * @return The bytes for requestContent.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestContentBytes() {
      java.lang.Object ref = requestContent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestContent_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestContent_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requestContent_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestContent_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest)) {
        return super.equals(obj);
      }
      io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest other = (io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest) obj;

      if (!getRequestContent()
          .equals(other.getRequestContent())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUEST_CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getRequestContent().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.github.aaronai.proto.SayHelloRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.github.aaronai.proto.SayHelloRequest)
        io.github.aaronai.proto.GreetingOuterClass.SayHelloRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.aaronai.proto.GreetingOuterClass.internal_static_io_github_aaronai_proto_SayHelloRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.aaronai.proto.GreetingOuterClass.internal_static_io_github_aaronai_proto_SayHelloRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest.class, io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest.Builder.class);
      }

      // Construct using io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        requestContent_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.aaronai.proto.GreetingOuterClass.internal_static_io_github_aaronai_proto_SayHelloRequest_descriptor;
      }

      @java.lang.Override
      public io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest getDefaultInstanceForType() {
        return io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest build() {
        io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest buildPartial() {
        io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest result = new io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.requestContent_ = requestContent_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest) {
          return mergeFrom((io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest other) {
        if (other == io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest.getDefaultInstance()) return this;
        if (!other.getRequestContent().isEmpty()) {
          requestContent_ = other.requestContent_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                requestContent_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object requestContent_ = "";
      /**
       * <code>string request_content = 1;</code>
       * @return The requestContent.
       */
      public java.lang.String getRequestContent() {
        java.lang.Object ref = requestContent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestContent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string request_content = 1;</code>
       * @return The bytes for requestContent.
       */
      public com.google.protobuf.ByteString
          getRequestContentBytes() {
        java.lang.Object ref = requestContent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestContent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string request_content = 1;</code>
       * @param value The requestContent to set.
       * @return This builder for chaining.
       */
      public Builder setRequestContent(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        requestContent_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string request_content = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestContent() {
        requestContent_ = getDefaultInstance().getRequestContent();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string request_content = 1;</code>
       * @param value The bytes for requestContent to set.
       * @return This builder for chaining.
       */
      public Builder setRequestContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        requestContent_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.github.aaronai.proto.SayHelloRequest)
    }

    // @@protoc_insertion_point(class_scope:io.github.aaronai.proto.SayHelloRequest)
    private static final io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest();
    }

    public static io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SayHelloRequest>
        PARSER = new com.google.protobuf.AbstractParser<SayHelloRequest>() {
      @java.lang.Override
      public SayHelloRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SayHelloRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SayHelloRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.aaronai.proto.GreetingOuterClass.SayHelloRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SayHelloResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.github.aaronai.proto.SayHelloResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string response_content = 1;</code>
     * @return The responseContent.
     */
    java.lang.String getResponseContent();
    /**
     * <code>string response_content = 1;</code>
     * @return The bytes for responseContent.
     */
    com.google.protobuf.ByteString
        getResponseContentBytes();
  }
  /**
   * Protobuf type {@code io.github.aaronai.proto.SayHelloResponse}
   */
  public static final class SayHelloResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.github.aaronai.proto.SayHelloResponse)
      SayHelloResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SayHelloResponse.newBuilder() to construct.
    private SayHelloResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SayHelloResponse() {
      responseContent_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SayHelloResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.aaronai.proto.GreetingOuterClass.internal_static_io_github_aaronai_proto_SayHelloResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.aaronai.proto.GreetingOuterClass.internal_static_io_github_aaronai_proto_SayHelloResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse.class, io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse.Builder.class);
    }

    public static final int RESPONSE_CONTENT_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object responseContent_ = "";
    /**
     * <code>string response_content = 1;</code>
     * @return The responseContent.
     */
    @java.lang.Override
    public java.lang.String getResponseContent() {
      java.lang.Object ref = responseContent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseContent_ = s;
        return s;
      }
    }
    /**
     * <code>string response_content = 1;</code>
     * @return The bytes for responseContent.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResponseContentBytes() {
      java.lang.Object ref = responseContent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(responseContent_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, responseContent_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(responseContent_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, responseContent_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse)) {
        return super.equals(obj);
      }
      io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse other = (io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse) obj;

      if (!getResponseContent()
          .equals(other.getResponseContent())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSE_CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getResponseContent().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.github.aaronai.proto.SayHelloResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.github.aaronai.proto.SayHelloResponse)
        io.github.aaronai.proto.GreetingOuterClass.SayHelloResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.github.aaronai.proto.GreetingOuterClass.internal_static_io_github_aaronai_proto_SayHelloResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.github.aaronai.proto.GreetingOuterClass.internal_static_io_github_aaronai_proto_SayHelloResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse.class, io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse.Builder.class);
      }

      // Construct using io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        responseContent_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.github.aaronai.proto.GreetingOuterClass.internal_static_io_github_aaronai_proto_SayHelloResponse_descriptor;
      }

      @java.lang.Override
      public io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse getDefaultInstanceForType() {
        return io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse.getDefaultInstance();
      }

      @java.lang.Override
      public io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse build() {
        io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse buildPartial() {
        io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse result = new io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.responseContent_ = responseContent_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse) {
          return mergeFrom((io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse other) {
        if (other == io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse.getDefaultInstance()) return this;
        if (!other.getResponseContent().isEmpty()) {
          responseContent_ = other.responseContent_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                responseContent_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object responseContent_ = "";
      /**
       * <code>string response_content = 1;</code>
       * @return The responseContent.
       */
      public java.lang.String getResponseContent() {
        java.lang.Object ref = responseContent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responseContent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string response_content = 1;</code>
       * @return The bytes for responseContent.
       */
      public com.google.protobuf.ByteString
          getResponseContentBytes() {
        java.lang.Object ref = responseContent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseContent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string response_content = 1;</code>
       * @param value The responseContent to set.
       * @return This builder for chaining.
       */
      public Builder setResponseContent(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        responseContent_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string response_content = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponseContent() {
        responseContent_ = getDefaultInstance().getResponseContent();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string response_content = 1;</code>
       * @param value The bytes for responseContent to set.
       * @return This builder for chaining.
       */
      public Builder setResponseContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        responseContent_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.github.aaronai.proto.SayHelloResponse)
    }

    // @@protoc_insertion_point(class_scope:io.github.aaronai.proto.SayHelloResponse)
    private static final io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse();
    }

    public static io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SayHelloResponse>
        PARSER = new com.google.protobuf.AbstractParser<SayHelloResponse>() {
      @java.lang.Override
      public SayHelloResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SayHelloResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SayHelloResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.github.aaronai.proto.GreetingOuterClass.SayHelloResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_aaronai_proto_SayHelloRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_github_aaronai_proto_SayHelloRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_aaronai_proto_SayHelloResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_github_aaronai_proto_SayHelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n io/github/aaronai/greeting.proto\022\027io.g" +
      "ithub.aaronai.proto\"*\n\017SayHelloRequest\022\027" +
      "\n\017request_content\030\001 \001(\t\",\n\020SayHelloRespo" +
      "nse\022\030\n\020response_content\030\001 \001(\t2m\n\010Greetin" +
      "g\022a\n\010SayHello\022(.io.github.aaronai.proto." +
      "SayHelloRequest\032).io.github.aaronai.prot" +
      "o.SayHelloResponse\"\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_github_aaronai_proto_SayHelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_github_aaronai_proto_SayHelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_github_aaronai_proto_SayHelloRequest_descriptor,
        new java.lang.String[] { "RequestContent", });
    internal_static_io_github_aaronai_proto_SayHelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_github_aaronai_proto_SayHelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_github_aaronai_proto_SayHelloResponse_descriptor,
        new java.lang.String[] { "ResponseContent", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
